### PR TITLE
 fixed: the image is not loaded in Readme

### PR DESCRIPTION
**Pull request by Romansth**
The issue of run.gif not loading in README.rtf doc has been fixed.

### CODE REVIEW

**Review by Aju100 — CHANGES_REQUESTED** [review]
HI @Romansth ,

Did you test on your machine and do share the screenshot of the output of it.

Regards,
Aju Tamang

**Comment by Aju100** [comment]
@Romansth , I request you to go [Contributing guidelines](https://asciju.readthedocs.io/en/latest/contributing.html) and change the branch too.

**Comment by Romansth** [comment]
Hi @Aju100 . I'm not pretty sure about testing the changes on my local machine since the changes will only be seen on readthedocs. Would you please elaborate?

**Comment by Aju100** [comment]
Hi @Romansth ,

You can use any rst extensions viewer of visual studio code to view the README file.
Talking about the building readthedocs locally, you can go through this [guide](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start). If you have any issues do let me know. Thanks

Regards,
Aju Tamang

**Pull request closed without merging**
